uploads = []

[[generated]]
id = "uMO5DiaI1YoOQhORDGT-N"
uri = "file://artifacts/flowdeck-mobile/assets/images/icon.png"
type = "image"
title = "flowdeck mobile app icon"

[[outputs]]
id = "3SGg9xCPDRz8S8MNfcnzu"
uri = "file://DOCUMENTATION.md"
type = "text"
title = "FlowDeck Documentation"

[[outputs]]
id = "QX9P4FZKRnVl_5Zci6_dM"
uri = "file://FlowDeck-Documentation.pdf"
type = "pdf"
title = "FlowDeck Documentation (PDF)"

[[outputs]]
id = "tq_MYwN3VlrGSTK2xsJ0D"
uri = "file://FlowDeck-Feature-Status.xlsx"
type = "table"
title = "FlowDeck Feature Status Table"
